### ISSUE TITLE
schlechter Kontrast

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/presentations#1]
dunkelgrau auf blau ist nicht besonders gut lesbar:
![screen1](https://cloud.githubusercontent.com/assets/1520891/10318733/24975f76-6c6b-11e5-83b8-997514886b02.png)

Wie wärs mit dunklem Schlagschatten und ggf. hellerem Grau?

**Comment by sedrubal** [comment]
Danke, mit Kontrasten hab ichs ned so... Ist jetzt weiß.
