### ISSUE TITLE
Inhaltliches

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/presentations#2]
- [x] "TODO Sauers Einweisungsbild"
- [x] Der QR Code wirkt deplatziert und der Hintergrund unpassend. Lieber stattdessen URL in die Mitte und größer, denn die sollen die Leute im Gedächtnis behalten. Hintergrund lieber blau, oder ein Bild?
- [x] da und dort noch Dinge streichen, und dafür noch ne Folie mit 3D-Drucker reintun? Hängen bleiben muss ja nicht viel mehr als: "Hinter den Hörsälen, fablab.fau.de, Laser, 3D-Druck"

**Comment by sedrubal** [comment]
Danke für die Punkte.

Kannst du wg. dem QR Code und dem Link evtl. dann gleich nochmal schauen? Mit 1eed6fc könnte es gefixt sein. Bei meinen Browsern hat es gut ausgesehen.

Und kannst du noch paar Sachen auflisten, die man streichen kann? Ich hab schon versucht, nur das Wichtigste rein zu tun, aber wenn 2 Leute aussortieren, ist das besser...

**Comment by mgmax** [comment]
ich meinte das mit dem QR schon so wie ich sagte... da wird doch nicht ernsthaft jemand den QR scannen...

**Comment by mgmax** [comment]
Die komplette folie "OFFENE WERKSTATT" kann auch weg.

**Comment by mgmax** [comment]
mein senf ist folgender:

die "DU SOLLTEST VORBEI KOMMEN, WENN..." könnte man auch relativ ersatzlos streichen, um zeit zu sparen. Ich denke das kann man auch einfach für die Schlussfolie sagen: "Wenn Ihr Interesse habt, schaut einfach mal vorbei. Mehr Infos findet ihr auch online: fablab.fau.de" [URL groß anzeigen, denn die leute können mit den augen keine QR codes lesen, und sind ziemlich sicher noch nicht interessiert genug um schnell einen QR aufzurufen.]

was vielleicht noch interessant anzubringen wäre - mündlich - unter sonstiges der punkt "fahrradwerkzeug und luft".

übrigens hat sich bei mir der kontrast nicht wirklich geändert (version vom buildserver), und bei 3d und sauer ist noch kein bild online. **edit**:  jetzt gehts

Letztlich ist es natürlich deine Präsentation, du musst also selber entscheiden was du davon umsetzt und was nicht.

**Comment by vale** [comment]
Ich habe die aktuelle version nicht vom build server und halte den kontrast für gut bild mit sauer ist drin
"fahrradwerkzeug und druckluft" ist sicher ein guter punkt, den ruhig noch mehr leute wissen dürfen

**Comment by vale** [comment]
neben der URL würde ich auf der letzten Slide auch noch den Fabcube plazieren, damit die leute das logo vielleicht mit "oh 3d druck" in Verbindung setzen

**Comment by sedrubal** [comment]
@mgmax Mit dem QR Code hab ich dich wohl falsch verstanden, sorry...  Da schauen wir nochmal, was man machen könnte...

Zeit müssen wir nicht sparen. Viel Inhalt bringt die "Vorbei Kommen" Folie nicht, aber muss sie auch nicht, da man ja keine Inhalte bringen soll, sondern nur nen guten Eindruck hinterlassen soll und ich hab mir damals gedacht, dass ich überhaupt keinen Plan habe, was die Gruppen von mir wollen, und drum finde ich die Folie gar nicht mal verkehrt.

Stimmt, die Luft wollte ich auch noch anbringen...

Weiß nicht, was mit dem Buildserver los ist, hab keine Zeit das zu fixen. Habs manuell angeregt.

Danke für die Hinweise!

**Comment by EmJay276** [comment]
Lass bei der Website Adresse das https:// weg einfach nur fablab.fau.de
Das merkt sich eh keiner/tippt eh keiner ein

Gruß
Michaeö

Am 07.10.2015 um 00:39 schrieb sedrubal:

**Comment by sedrubal** [comment]
jop, guter Einwand  :+1: fixed with aea2ae9
