### ISSUE TITLE
Makefile für img/ funktioniert nicht unter Debian / auf dem Buildserver

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/presentations#3]
- svg2pdf gibts nicht für Debian. Man könnte auch inkscape aufrufen, ist zwar hässlich aber kann dafür alles
- Das Makefile für img/ wird garnicht aufgerufen.

**Comment by sedrubal** [comment]
Ich würde `rsvg-convert` aus dem paket `librsvg2-bin` empfehlen. Nachdem ich aber auch nicht weiß, für was das gut ist/war, hab ich das Makefile gelöscht.
